spring:
  rabbitmq:
    addresses: 'localhost:5672'
    username: 'guest'
    password: 'guest'
  cloud.stream:
    default-binder: rabbit
    function:
      definition: sendDemo;receiveDemo
    bindings:
      sendDemo-out-0:
        destination: demo_topic
      receiveDemo-in-0:
        destination: demo_topic
